name: Close Jira issue

on:
  issues:
    types:
      - closed

jobs:
  close-issue:
    name: Close Jira issue
    runs-on: ubuntu-latest

    steps:
      # 1. 작성자 GitHub ID → Jira 이메일 매핑
      - name: Set Jira user email from GitHub ID
        id: set-jira-email
        run: |
          AUTHOR="${{ github.event.issue.user.login }}"
          echo "이슈 작성자: $AUTHOR"

          case "$AUTHOR" in
            "lee-nakyung") EMAIL="lnk5324@hansung.ac.kr" ;;
            "bbzjun") EMAIL="wowns564@gmail.com" ;;
            "sungheonkim") EMAIL="tjdgjswkd@gmail.com" ;;
            "ahcgnoej") EMAIL="jinchajung123456@gmail.com" ;;
            *) EMAIL="wowns564@gmail.com" ;;
          esac

          echo "JIRA_USER_EMAIL=$EMAIL" >> $GITHUB_ENV

      # 2. Jira 로그인
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ env.JIRA_USER_EMAIL }}

      # 3. 제목에서 Jira 키 추출
      - name: Extract Jira issue key from GitHub issue title
        id: extract-key
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          JIRA_KEY=$(echo "$ISSUE_TITLE" | grep -oE '[A-Z]+-[0-9]+')
          echo "JIRA_KEY=$JIRA_KEY" >> $GITHUB_ENV

      # 4. Jira 이슈 상태를 '완료'로 전환
      - name: Close Jira issue
        if: env.JIRA_KEY != ''
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ env.JIRA_KEY }}
          transition: 완료
